server:
  port: 8081

spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mascotas_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mascotas_db
    username: postgres
    password: postgres
  cloud:
    discovery:
      enabled: true
      service-id: pet-service

logging:
  level:
    com.perro.pet: DEBUG